spring.application.name=nexuserp

server.port=8080


# Neon.tech Bulut Bağlantısı
spring.datasource.url=jdbc:postgresql://ep-small-boat-at8dndwj.c-9.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xvMO81nYQkyE

# JPA ve Log Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true